modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="COFH Don't Be A Jerk"
[[mods]] #mandatory
    modId="ece" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="EnhancedCeletialEnhancement" #mandatory
    updateJSONURL="" #optional
    authors="winterSteve25" #optional
    description='''
    logoFile="ece_logo.png"
'''
[[dependencies.ece]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[36,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.ece]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ece]]
    modId="enhancedcelestials"
    mandatory=true
    versionRange="[1.0.4,)"
    ordering="NONE"
    side="BOTH"